CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);
INSERT INTO roles(name) VALUES
('ROLE_VIEWER'),
('ROLE_LOCATION_ADMIN'),
('ROLE_ADMIN'),
('ROLE_DISTRIBUTION_ADMIN'),
('ROLE_INVENTORY_ADMIN');
